parserOptions:
  ecmaVersion: 6
env:
  node: true
  es6: true
plugins:
  - prettier
  - react
  - import
extends:
  - plugin:react/recommended
  - plugin:import/errors
  - prettier
  - prettier/react
parser: babel-eslint
rules:
  # prettier
  prettier/prettier:
    - 2
    -
      singleQuote: true
      trailingComma: none
      semi: false
      printWidth: 120
  # rules
  prefer-const: 2
  no-unused-vars: 2
  no-multiple-empty-lines:
    - 2
    - max: 1
  # react
  react/prefer-stateless-function: 2
  # import
  import/newline-after-import: 2
  import/imports-first: 2
  import/no-dynamic-require: 2
  import/no-extraneous-dependencies: 2
  import/no-mutable-exports: 2
  import/no-commonjs: 2
