export const VARCHAR = `
$dictionary['<%= module %>']['fields']['<%= name %>'] = [
    'required' => <%= required === '1' ? 'true' : 'false' %>,
    'name' => '<%= name %>',
    'vname' => 'LBL_<%= name.toLocaleUpperCase() %>',
    'type' => 'varchar',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'default' => '<%= defaultValue %>',
    'full_text_search' => [
        'enabled' => '0',
        'boost' => '1',
        'searchable' => false,
    ],
    'calculated' => false,
    'len' => '<%= len || 255 %>',
    'size' => '20',
];
`

export const BOOL = `
$dictionary['<%= module %>']['fields']['<%= name %>'] = [
    'required' => <%= required === '1' ? 'true' : 'false' %>,
    'name' => '<%= name %>',
    'vname' => 'LBL_<%= name.toLocaleUpperCase() %>',
    'type' => 'bool',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'default' => <%= defaultValue === '1' ? 'true' : 'false' %>,
    'calculated' => false,
    'len' => '255',
    'size' => '20',
];
`

export const DROPDOWN = `
$dictionary['<%= module %>']['fields']['<%= name %>'] = [
    'required' => <%= required === '1' ? 'true' : 'false' %>,
    'name' => '<%= name %>',
    'vname' => 'LBL_<%= name.toLocaleUpperCase() %>',
    'type' => 'enum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'default' => '<%= defaultValue %>',
    'calculated' => false,
    'len' => <%= len || 100 %>,
    'size' => '20',
    'options' => '<%= name %>_list',
    'dependency' => false,
];
`

export const DATE = `
$dictionary['<%= module %>']['fields']['<%= name %>'] = [
    'required' => <%= required === '1' ? 'true' : 'false' %>,
    'name' => '<%= name %>',
    'vname' => 'LBL_<%= name.toLocaleUpperCase() %>',
    'type' => 'date',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'size' => '20',
    'enable_range_search' => false,
];
`

export const DATETIME = `
$dictionary['<%= module %>']['fields']['<%= name %>'] = [
    'required' => <%= required === '1' ? 'true' : 'false' %>,
    'name' => '<%= name %>',
    'vname' => 'LBL_<%= name.toLocaleUpperCase() %>',
    'type' => 'datetimecombo',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'size' => '20',
    'enable_range_search' => false,
    'dbType' => 'datetime',
];
`

export const INT = `
$dictionary['<%= module %>']['fields']['<%= name %>'] = [
    'required' => <%= required === '1' ? 'true' : 'false' %>,
    'name' => '<%= name %>',
    'vname' => 'LBL_<%= name.toLocaleUpperCase() %>',
    'type' => 'int',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'default' => '',
    'full_text_search' => [
        'enabled' => '0',
        'boost' => '1',
        'searchable' => false,
    ],
    'calculated' => false,
    'len' => '<%= len || 255 %>',
    'size' => '20',
    'enable_range_search' => false,
    'disable_num_format' => '',
    'min' => false,
    'max' => false,
];
`

export const RADIO = `
$dictionary['<%= module %>']['fields']['<%= name %>'] = [
    'required' => <%= required === '1' ? 'true' : 'false' %>,
    'name' => '<%= name %>',
    'vname' => 'LBL_<%= name.toLocaleUpperCase() %>',
    'type' => 'radioenum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'default' => '<%= defaultValue %>',
    'calculated' => false,
    'len' => <%= len || 100 %>,
    'size' => '20',
    'options' => '<%= name %>_list',
    'dbType' => 'enum',
    'separator' => '<br>',
];
`

export const TEXTAREA = `
$dictionary['<%= module %>']['fields']['<%= name %>'] = [
    'required' => <%= required === '1' ? 'true' : 'false' %>,
    'name' => '<%= name %>',
    'vname' => 'LBL_<%= name.toLocaleUpperCase() %>',
    'type' => 'text',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'default' => '<%= defaultValue %>',
    'full_text_search' => [
        'enabled' => '0',
        'boost' => '1',
        'searchable' => false,
    ],
    'calculated' => false,
    'size' => '20',
    'studio' => 'visible',
    'rows' => '4',
    'cols' => '20',
];
`

export const PHONE = `
$dictionary['<%= module %>']['fields']['<%= name %>'] = [
    'required' => <%= required === '1' ? 'true' : 'false' %>,
    'name' => '<%= name %>',
    'vname' => 'LBL_<%= name.toLocaleUpperCase() %>',
    'type' => 'phone',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'default' => '<%= defaultValue %>',
    'full_text_search' => [
        'enabled' => '0',
        'boost' => '1',
        'searchable' => false,
    ],
    'calculated' => false,
    'len' => '<%= len || 255 %>',
    'size' => '20',
    'dbType' => 'varchar',
];
`

export const CURRENCY = `
$dictionary['<%= module %>']['fields']['<%= name %>'] = [
    'required' => <%= required === '1' ? 'true' : 'false' %>,
    'name' => '<%= name %>',
    'vname' => 'LBL_<%= name.toLocaleUpperCase() %>',
    'type' => 'currency',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'default' => 0,
    'calculated' => false,
    'len' => <%= len || 26 %>,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
    'related_fields' => [
        'currency_id',
        'base_rate',
    ],
];

$dictionary['<%= module %>']['fields']['currency_id'] = [
    'required' => false,
    'name' => 'currency_id',
    'vname' => 'LBL_CURRENCY_ID',
    'type' => 'currency_id',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 36,
    'size' => '20',
    'dbType' => 'id',
    'studio' => false,
    'function' => 'getCurrencies',
    'function_bean' => 'Currencies',
];

$dictionary['<%= module %>']['fields']['base_rate'] = [
    'required' => false,
    'name' => 'base_rate',
    'vname' => 'LBL_CURRENCY_RATE',
    'type' => 'decimal',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 26,
    'size' => '20',
    'enable_range_search' => false,
    'precision' => 6,
    'label' => 'LBL_CURRENCY_RATE',
    'studio' => false,
];
`

export const MULTISELECT = `
$dictionary['<%= module %>']['fields']['<%= name %>'] = [
    'required' => <%= required === '1' ? 'true' : 'false' %>,
    'name' => '<%= name %>',
    'vname' => 'LBL_<%= name.toLocaleUpperCase() %>',
    'type' => 'multienum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'default' => '^^',
    'calculated' => false,
    'size' => '20',
    'options' => '<%= name %>_list',
    'dependency' => '',
    'isMultiSelect' => true,
];
`

export const RELATE = `
$dictionary['<%= module %>']['fields']['<%= name %>_id'] = [
    'required' => false,
    'name' => '<%= name %>_id',
    'vname' => 'LBL_<%= name.toLocaleUpperCase() %>_ID',
    'type' => 'id',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => 1,
    'audited' => false,
    'reportable' => false,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 36,
    'size' => '20',
];

$dictionary['<%= module %>']['fields']['<%= name %>'] = [
    'required' => <%= required === '1' ? 'true' : 'false' %>,
    'source' => 'non-db',
    'name' => '<%= name %>',
    'vname' => 'LBL_<%= name.toLocaleUpperCase() %>',
    'type' => 'relate',
    'massupdate' => false,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => '255',
    'size' => '20',
    'id_name' => '<%= name %>_id',
    'ext2' => '<%= relateModule %>',
    'module' => '<%= relateModule %>',
    'rname' => 'name',
    'quicksearch' => 'enabled',
    'studio' => 'visible',
];
`

export default {
  VARCHAR,
  BOOL,
  DROPDOWN,
  DATE,
  DATETIME,
  INT,
  RADIO,
  TEXTAREA,
  PHONE,
  CURRENCY,
  MULTISELECT,
  RELATE,
}
